### ISSUE TITLE
Cannot launch manual_control.py inside of docker

### ISSUE THREAD

**Issue by weihu8687** [AuroAi/carla_apollo_bridge#11]
Hi, when I run this step

```shell
# run in carla-apollo container in another terminal:

cd ~/carla_apollo_bridge
python examples/manual_control.py
```

It's blocked by below error, I think the root cause is the script cannot launch the pygame window inside of the carla-apollo docker image?

```shell
oot@34bb81f125f5:~/carla_apollo_bridge# python examples/manual_control.py 
pygame 2.0.0 (SDL 2.0.12, python 2.7.15)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO: listening to server 172.17.0.1:2000

Welcome to CARLA manual control.

Use ARROWS or WASD keys for control.

    W            : throttle
    S            : brake
    AD           : steer
    Q            : toggle reverse
    Space        : hand-brake
    P            : toggle autopilot
    M            : toggle manual transmission
    ,/.          : gear up/down

    TAB          : change sensor position
    C            : change weather (Shift+C reverse)

    R            : toggle recording images to disk

    CTRL + R     : toggle recording of simulation (replacing any previous)
    CTRL + P     : start replaying last recorded simulation
    CTRL + +     : increments the start time of the replay by 1 second (+SHIFT = 10 seconds)
    CTRL + -     : decrements the start time of the replay by 1 second (+SHIFT = 10 seconds)

    F1           : toggle HUD
    H/?          : toggle help
    ESC          : quit

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  94
  Current serial number in output stream:  95
```
Any suggestions to show the pygame window correctly? Thanks.

**Comment by weihu8687** [comment]
BTM, my host machine uses nvidia-driver 410.78 and CUDA 10.0.

**Comment by wangzhensuo** [comment]
I also meet this problem. try to run more times ,and it will be run ok in my experence.

**Comment by wangzhensuo** [comment]
> 
> 
> BTM, my host machine uses nvidia-driver 410.78 and CUDA 10.0.

I also meet this problem. try to run more times ,and it will be run ok in my experence.

**Comment by weihu8687** [comment]
> > BTM, my host machine uses nvidia-driver 410.78 and CUDA 10.0.
> 
> I also meet this problem. try to run more times ,and it will be run ok in my experence.

unfortunately I have tried several times but the error log still exists, I have stopped trying, and use a local carla server instead (I have built the carla server from source but I think use the pre-build tar.gz from carla github repo directly would be fine too).

**Comment by AngelJA** [comment]
Hi, this seems like an nvidia-docker issue.  Are you able to run other GUI's from docker that use the GPU?  Do you see your GPU listed when you run nvidia-smi in the docker container?

**Comment by weihu8687** [comment]
nvidia-smi works in the carla-apollo docker container, but each time I run the **python manual_control.py** it reports error:

```shell
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

```shell
root@53235e8a887c:~/carla_apollo_bridge# nvidia-smi 
Sat Oct 31 02:36:47 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
| 38%   71C    P0    51W / 120W |   1120MiB /  6075MiB |     35%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by weihu8687** [comment]
Finally I find the solution by referring to:

https://github.com/SoonminHwang/dockers/issues/1#issue-350292669

In short:

```shell
Connect nvidia-driver volume when docker image runs, add proper path to ${PATH} and ${LD_LIBRARY_PATH}.
```

wish it helps if anybody run into this issue, cheers~

**Comment by curio-code** [comment]
@weihu8687 I am facing the same problem and followed the solution you suggested but after `docker run -it \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \\
    --privileged \
    -e DISPLAY=$DISPLAY \
    -v /usr/lib/nvidia-384:/usr/lib/nvidia-384 \
    -v /usr/lib32/nvidia-384:/usr/lib32/nvidia-384 \
    --device /dev/dri \
carla-apollo`

In the container I couldn't access the `cd ~/carla_apollo_bridge` folder

Could you please post the exact commands you used. 
Thanks in advance.

**Comment by marcusvinicius178** [comment]
hi @weihu8687 I had the same issue, however I did not understand how to redo the command of the link you shared for my specific machine. Could you please share the commands you have used?

**Comment by marcusvinicius178** [comment]
Hi @AngelJA , @weihu8687 , @wangzhensuo 

I am struggling with these issues in the last week to connect CARLA with APollo and launch this simulator script (manual_control.py)

Can you please help me? I have already tried a lot of approaches: https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update/566522#566522
Any one of them worked.

I think the  **Docker commands you suggested* can work*, however, **did not work on my system**. I tried to adjust the commands from this link https://github.com/SoonminHwang/dockers/issues/1#issue-350292669 you have shared to my case-driver-system:

**In my case I am using NVidia-470** and in the folder /usr/lib I have the folder "nvidia" not the folder "nvidia-470"....
Then I have modified the command and issued:

**Command 1**

docker run -it \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \\
    --privileged \
    -e DISPLAY=$DISPLAY \
    -v /usr/lib/nvidia:/usr/lib/nvidia \
    -v /usr/lib32/nvidia:/usr/lib32/nvidia \
    --device /dev/dri \
    carla-server

**Command 2**

export PATH="/usr/lib/nvidia/bin":${PATH}
export LD_LIBRARY_PATH="/usr/lib/nvidia/usr/lib32/nvidia":${LD_LIBRARY_PATH}


I have added in addition other flags to enable NVIDIA and opengl library communicates with Docker, however the error persists...

In addition, I Have already reinstalled nvidia-drivers, installed clang compilers, ninja-build, nvidia-container toolkit, nvidia-docker2, libvulkan, mesa-grip driver, have also added ENV Nvidia_capabilities, display in Docker image, have exported paths, set symbolic links to libGl versions, restarted docker,daemon and gdm, etc, etc but nothing worked :(
