### ISSUE TITLE
The carla_apollo_bridge/carla-python-0.9.6 Folder is empty

### ISSUE THREAD

**Issue by weihu8687** [AuroAi/carla_apollo_bridge#12]
Hi, from the ReadMe there should be a carla-python-0.9.6 folder inside of the carla-apollo container, but I find the folder is empty.

```shell
# run in another carla-apollo container terminal:
cd ~/carla_apollo_bridge/carla-python-0.9.6
```
I confirm again that I have followed all the instructions, did I miss anything? thanks.

**Comment by AngelJA** [comment]
Maybe there was an error when it tried to pull the API.  Try deleting the carla-python-0.9.6 directory and run get_python_api.sh in the docker directory.

**Comment by weihu8687** [comment]
Thanks for reply, yes, looks like the script runs into problem and I copy it manually.

```shell
# on host machine
docker cp  carla-server:/home/carla/PythonAPI   .
docker cp PythonAPI/*  carla-apollo:/root/carla_apollo_bridge/carla-python-0.9.6/
```

**Comment by weihu8687** [comment]
verified that manual copy works, thanks.
