### ISSUE TITLE
Localization without IMU sensor

### ISSUE THREAD

**Issue by trieuthachvu** [AuroAi/carla_apollo_bridge#19]
As I understand that Apollo uses GPS, IMU and Lidar to do the localization. How did you do the localization without IMU sensor?

**Comment by AngelJA** [comment]
Apollo's localization module isn't actually being run here. The ground truth vehicle position is just being written to the localization channel.

**Comment by Thinsheep** [comment]
Thanks.
I am interested in this method. Which file in the source code does this kind of work?

**Comment by AngelJA** [comment]
https://github.com/AuroAi/carla_apollo_bridge/blob/master/carla_cyber_bridge/ego_vehicle.py#L308

Here is where the localization message is 'written'. Start looking there :)

**Comment by Thinsheep** [comment]
Thanks :)

**Comment by marcusvinicius178** [comment]
Hi @AngelJA, @Thinsheep how to enable the run of localization module as the other ones (routing, prediction,planning...) in dreamview?  I mean use the localization module effectively instead the ground truth.

What must be changed in the bridge related codes?

I wish to use different apollo localization systems and features:

- 2 Systems Localization ( GNSS + IMU)
- 3 Systems Localization (GNSS + IMU + LIDAR)

- Play around with the parameters altitude & intensity (LiDAR) and GNSS options
Thanks in advance

**Comment by daohu527** [comment]
In fact, if you test the localization, I think it is better to use the actual vehicle or use the bag.

I don't know much about gnss emulation, in fact I haven't seen other emulators that emulate gnss messages. also lidar localization is implemented with a prior map, so you should first build the map and then use ndt or some other algorithm to localization.

You need to assess whether it takes that much effort to verify
