### ISSUE TITLE
About auroai/cyber

### ISSUE THREAD

**Issue by tangcy98** [AuroAi/carla_apollo_bridge#2]
I found that in docker/Dockerfile "FROM auroai/cyber:v5.0.0.1".
It will lead to "manifest unknown" problem when building.
Maybe we should correct it to "FROM auroai/cyber:v5.0.0".

**Comment by AngelJA** [comment]
Thanks for catching this.  I think this was for a newer image which we may have not needed after all.  I'll correct when I get a chance to test.

**Comment by AngelJA** [comment]
changed to tag v5.0.0
