### ISSUE TITLE
How to see all ros topics when I run the  bridge

### ISSUE THREAD

**Issue by lushunn** [AuroAi/carla_apollo_bridge#21]
Thank you.
When I use `rostopic list `to show the rostopic in carla side, it show nothing, so how can I see the topic messages when I run the bridge?

**Comment by AngelJA** [comment]
Hi. Since this is an Apollo CyberRT bridge, there is no ROS involved at all. The equivalent to ROS topics in CyberRT is channels. To see the channels you can try `cyber_monitor` or possibly `cyber channel list` (not sure about that last one).

**Comment by lushunn** [comment]
> Hi. Since this is an Apollo CyberRT bridge, there is no ROS involved at all. The equivalent to ROS topics in CyberRT is channels. To see the channels you can try `cyber_monitor` or possibly `cyber channel list` (not sure about that last one).

Thank you for your reply~
