### ISSUE TITLE
libGL error: No matching fbConfigs or visuals found, failed to load driver: swrast

### ISSUE THREAD

**Issue by marcusvinicius178** [AuroAi/carla_apollo_bridge#30]
Hi I am following this tutorial: https://github.com/AuroAi/carla_apollo_bridge

Everything works until the usage step to run the following script:

`# run in carla-apollo container in another terminal:

cd ~/carla_apollo_bridge
python examples/manual_control.py`

After running it I get the error:

![libGL_error](https://user-images.githubusercontent.com/43826438/150880287-aa8e3139-9864-4c43-b98e-4c42b2dde3f0.png)

My Nvidia-cuda setup is below. I am using **TESLA GPU**

![image](https://user-images.githubusercontent.com/43826438/150880804-769e9342-bad4-425e-9811-3bf187153a43.png)

I have followed the Nvidia-Docker installation: https://docs.docker.com/install/linux/docker-ce/ubuntu/

and installed the **nvidia-docker2** 

However there are some discussions in the following links, that maybe this is deprecated to docker >19.02 and the **nvidia=container-toolkit** should be installed instead:  
.  My docker is :
`Docker version 20.10.12, build e91ed57
`

1 -https://github.com/NVIDIA/nvidia-docker/issues/1268

2 - https://www.pugetsystems.com/labs/hpc/Workstation-Setup-for-Docker-with-the-New-NVIDIA-Container-Toolkit-nvidia-docker2-is-deprecated-1568/

 I have also read the Nvidia with Docker **usage recommendation**: https://github.com/nvidia/nvidia-docker

as well as read some solutions that worked for other guys: 
 
1 - https://github.com/AuroAi/carla_apollo_bridge/issues/11
2 - https://github.com/SoonminHwang/dockers/issues/1#issue-350292669
3 - https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update/566522#566522

**Unfortunately ** this didn't work for me. 

I have runned the carla-server container with the following additional flags (instead the original of tutorial):

`docker run  --rm -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.6`

And I have modified the DOCKERFILE from carla_apollo_bridge/docker folder, adding **Environmental variables (ENV)** below:

![image](https://user-images.githubusercontent.com/43826438/150881498-985d56a1-768a-449c-9f0b-19c1267dad77.png)

I have also used **-e DISPLAY=$DISPLAY ** instead ENV SDL_VIDEODRIVER='offscreen', but any result...

I have no idea why this error persists and how to fix it.

Is it because should be installed nvidia-container-toolkit **instead** nvidia-docker2?
or is some docker run **flag wrong or missing**?

Some driver missing?         mesa-utils, libvulkan1, libgl1-mesa-dri? I tried a lot of them and anything worked...

Can someone help?

**Comment by daohu527** [comment]
Does carla support not starting a graphical interface? It is really not very friendly to start a graphical interface in docker

In fact, if it's just a cyber framework, you can do without docker at all

**Comment by marcusvinicius178** [comment]
I cannot. I tried to run CARLA 0.9.6 along the Apollo5.0 (modified branch with the cyber bridge): 

`git clone https://github.com/auroai/apollo --single-branch -b carla`

And answering to your question, yes they support graphical interface with Apollo 5.0:
https://youtu.be/QR__C8voIQg


But to run from **source** there is an issue in running the **run_bridge.py** file. This script use a lot of modules, that are built just inside the Docker image. Therefore it is not possible to start this bridge outside docker. It is going to **raise in NoModuleFoundError and Import Errors**

![image](https://user-images.githubusercontent.com/43826438/150891146-6e46c676-2e5d-42ba-9fff-0d469c7e8802.png)

The tutorial was done to work with docker: https://github.com/AuroAi/carla_apollo_bridge
even that they say "it is possible to run from source" as far as I understood...

My last attempts was modify my docker image:

![image](https://user-images.githubusercontent.com/43826438/150890862-b420a527-14a7-4b96-a104-95e8dacc757d.png)

And start the container with these docker run flags:

`docker run  -it --rm  --privileged -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /usr/lib/nvidia:/usr/lib/nvidia --device /dev/dri -e SDL_VIDEO_GL_DRIVER= libGL.so.1.7.0 -e DISPLAY=$DISPLAY -e NVIDIA_VISIBLE_DEVICES=all -e  NVIDIA_DRIVER_CAPABILITIES=all --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.6`


In addition I have issued the following commands (related to fix this issue)

Inside docker:

```
export PATH="/usr/lib/nvidia/bin":${PATH}
export LD_LIBRARY_PATH="/usr/lib/:/usr/lib32/nvidia":${LD_LIBRARY_PATH}
```

Tried to pull the cuda-gl image:

`docker pull nvidia/cudagl:11.4.2-base-ubuntu20.04`

The command below worked, then showed everything is fine with GPU:
LIBGL_DEBUG=verbose glxgears

Tried to recover the symbolic links (recommended)


```
sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1.0  /usr/local/lib/libGL.so.1.7.0
sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so  /usr/local/lib/libGL.so.1
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/nvidia"
```

Installed this module:

`sudo apt-get install libgl1-mesa-glx
`



Anything worked. 

The "good" news is that I had the same problems in my laptop, and doing the steps I have showed now... reinstalling Nvidia-drivers,etc worked...and the LibGL error disappeared!

However I need to set this in our enterprise remote computer....that has a better GPU, RAM, system etc than mine. But for some reason the same steps are not working in this AWS remote machine...
I am trying to compare with my personal laptop to see what is different, but I cannot not see anything different.

Some idea @daohu527 

Thanks to try to help me! I really appreciate that

**Comment by daohu527** [comment]
Seems to be a nvidia driver and container issue, I'm also confused about using a GUI in a container, it's better to avoid it, or you'll face a lot of adaptation issues

**Comment by marcusvinicius178** [comment]
Hi @daohu527 you are right it was not easy....after read a lot about Docker and try numerous things I got it (2 weeks ago, I forgot to put here the solution).

For my cloud machine (AWS) what worked was:

**1:** Run the carla-server container with the following flags:

`docker run -it  --name=carla-server --privileged  -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /usr/lib/nvidia:/usr/lib/nvidia --device /dev/dri --rm -e __NV_PRIME_RENDER_OFFLOAD=1 -e __GLX_VENDOR_LIBRARY_NAME=nvidia -e DISPLAY=$DISPLAY  -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.6`

**instead** the tutorial command (DO NOT USE the COMMAND below)

`docker run --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.6`

In addition, the second step is needed:

**2:** Modify The Dockerfile inside **carla_apollo_bridge/docker** folder and **Add these Environment Variables** in the bottom of the file:


```
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
ENV SDL_VIDEO_GL_DRIVER = libGL.so.1.7.0  #libGL.so.1
ENV DISPLAY=$DISPLAY
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/nvidia"
ENV  __NV_PRIME_RENDER_OFFLOAD=1
ENV __GLX_VENDOR_LIBRARY_NAME=nvidia
```
 

I guess just the first 2 ENV are enough, however, I guess the addition of other ones brought more stability to open the pygame simulator. In addition a third step could be added, however it can crash a virtual machine (happened with me). It is **removing the xorg.conf** file inside **/etc/X11** folder

The problem is kind of 90% fixed because sometimes the simulator does not open at first attempt, pointing the same GLX communication issue...however repeating the command twice or ever three or more times, the simulator will open and work....
Just a docker expert can resolve this 100%, but for me it working is enough...

**Comment by daohu527** [comment]
Great job, thanks for sharing : )

**Comment by zzk525** [comment]
感谢，解决了我的问题。

**Comment by huangwei2000** [comment]
> 你好@daohu527你是对的，这并不容易......在阅读了大量关于 Docker 的文章并尝试了许多方法后，我终于明白了（2 周前，我忘了在这里放上解决方案）。
> 
> 对于我的云机器（AWS），有效的是：
> 
> **1：**使用以下标志运行 carla-server 容器：
> 
> `docker run -it --name=carla-server --privileged -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /usr/lib/nvidia:/usr/lib/nvidia --device /dev/dri --rm -e __NV_PRIME_RENDER_OFFLOAD=1 -e __GLX_VENDOR_LIBRARY_NAME=nvidia -e DISPLAY=$DISPLAY -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.6`
> 
> **而是使用**教程命令（不要使用下面的命令）
> 
> `docker run --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.6`
> 
> 另外，还需要第二步：
> 
> **2：修改****carla_apollo_bridge/docker**文件夹中的 Dockerfile ，并在文件底部**添加以下环境变量：**
> 
> ```
> ENV NVIDIA_VISIBLE_DEVICES all
> ENV NVIDIA_DRIVER_CAPABILITIES all
> ENV SDL_VIDEO_GL_DRIVER = libGL.so.1.7.0  #libGL.so.1
> ENV DISPLAY=$DISPLAY
> ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/nvidia"
> ENV  __NV_PRIME_RENDER_OFFLOAD=1
> ENV __GLX_VENDOR_LIBRARY_NAME=nvidia
> ```
> 
> 我猜前 2 个 ENV 就够了，但是我猜添加其他 ENV 可以为打开 pygame 模拟器带来更多稳定性。此外，可以添加第三个步骤，但是它可能会使虚拟机崩溃（我遇到过这种情况）。它正在删除**/etc/X11**文件夹中的**xorg.conf文件******
> 
> 该问题已修复 90%，因为有时模拟器在第一次尝试时无法打开，指向相同的 GLX 通信问题...但是重复该命令两次或三次或更多次，模拟器将打开并工作.... 只有 docker 专家才能 100% 解决这个问题，但对我来说，它能工作就足够了...

我也解决了 谢谢
