### ISSUE TITLE
connection time-out error

### ISSUE THREAD

**Issue by junyeonwon1** [AuroAi/carla_apollo_bridge#32]
Hello. I am trying to run apollo on Carla Simulator. 

I installed apollo, carla, and carla_apollo_bridge by following the instruction.

I think all of them were installed properly. However, when I execute 'examples/run_bridge.py' in docker container, the error happens.

The error is 'Error: time-out of 30000ms while waiting for the simulator, make sure the simulator is ready and connected to 172.17.0.1:2000' and it comes from bridge = CarlaCyberBridge(carla_world=client.get_world(), params=params) of examples/run_bridge.py.
When I execute 'docker ps' in a local terminal, carla-apollo and carla-server are running. 

Do you have any idea to resolve this problem? Or, are there any other ways to check whether everything is installed properly?

Thanks for your help in advance! :)

**Comment by 2019211753** [comment]
how did u solve it？please tell me~thanks!

**Comment by junyeonwon1** [comment]
Sorry. I did not use Carla due to this problem. Instead, I used LGSVL.

**Comment by 2019211753** [comment]
> Sorry. I did not use Carla due to this problem. Instead, I used LGSVL.

In my WSL and 1080Ti, the carla-simulator crashed because of low video Memory. I switched to 3080 and solved it successfully.
Besides, Is LGSVL still available right now? Could you please provide a brief explanation of how to use LGSVL or where can i get it? Thanks!
